### PR TITLE
Changed generator to be easier to fork the wallet

### PR DESCRIPTION
**Pull request by Watt3r**

### CODE REVIEW

**Comment by Watt3r** [comment]
Updated!

**Comment by Sajo8** [comment]
Wait where'd the restore from keys button go?

**Comment by Sajo8** [comment]
Will this be replacing the current paper wallet generator? Or can we set this up as an alternative paper wallet generator? (turtlecoin.lol/paper maybe)

**Comment by Watt3r** [comment]
This PR will be closed, @ChrisCrypto made a better implementation of this idea.

**Pull request closed without merging**
